baseURL: "https://example.com"
languageCode: "en-us"
title: "Handyan"
theme: "./.."
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 2

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."
  copyright: "2021"

  # Navbar Menus
  customMenus:
    - name: "About"
      Url: "/#"
    - name: "Blog"
      Url: "/blog"

  # social
  socialicontop: false
  name: "Handyan"
  github: "https://github.com/HandyanDzn"
  linkedin: "https://linkedin.com"
  twitter: "https://twitter.com/"
  instagram: "https://instagram.com/"
  facebook: "https://www.facebook.com/profile.php?id=100005013346155"

  # About
  profile_image: "/images/profile.webp"
  descripe_l1_person: "Manda uma descrição dps, corno"
  descripe_l2_person: ""

  useresume: true
  customname: ""
  resumelink: "/resume.pdf"

  # Things I do
  usedothings: true
  Things:
    - logo: 
      title: Coisa que você faz 1
      description: Descrição 1
      #url: 

    - logo: 
      title: Coisa que você faz 2
      description: Descrição 2
      #url: 

    - logo: 
      title: Coisa que você faz 2
      description: Descrição 3
      #url: 

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
